### ISSUE TITLE
not working on Windows 7 

### ISSUE THREAD

**Issue by severak** [jart/cosmopolitan#19]
you get this error message when running both from CLI or double click:

![win7ape](https://user-images.githubusercontent.com/615685/103207510-ce010b00-48fe-11eb-982d-2ee8de887ee9.png)

**Comment by jart** [comment]
Thanks for the report. I need to update some of these imports to go through Kernel32. Might I ask which version of Windows you're running?

**Comment by severak** [comment]
Windows 7 Ultimate 64-bit SP1

**Comment by jart** [comment]
Oh duh (forgot to read the title). I see what the problem is. I'm going to have a fix right up for you in a jiffy.

**Comment by jart** [comment]
I'm reasonably certain I've fixed the problem *a priori* since I don't have access to a Windows 7 box at this moment. I pushed new binaries for my various projects to https://justine.lol. Could you give it a try and let me know if it works for you? Easiest way to test that would be to download https://justine.lol/apelife/index.html and give it a run.

**Comment by jart** [comment]
Oh for what it's worth, since the documentation page doesn't make this obvious yet, download https://justine.storage.googleapis.com/apelife/apelife-2020-11-28.com and  https://justine.storage.googleapis.com/apelife/tm.lif and then run `apelife-2020-11-28.com tm.lif` on the command prompt. It's also possible to click the icon in the top left corner. That program links a bunch of WIN32 APIs so I'll be really happy if works. Please note some other programs, like the Blinkenlights TUI, really do require Windows 10 in some ways, since it's only on Windows 10 that the Command Prompt supports ANSI colors and VT100 codes. But it'll still probably be fine if you run it in something like mintty.

**Comment by severak** [comment]
Still getting same error, now entry point `AddVectoredExceptionHandler` could not be found.

Also - it seems that Firefox really don't like some of these files and tries to prevent me from downloading them.

**Comment by jart** [comment]
I'm not sure what's happening there since `AddVectoredExceptionHandler` has been around since Windows XP. We might need to find someone to help us with this, until I can find where I put my Windows 7 install disk.

**Comment by paususe** [comment]
@jart You can download a free Windows 7 VM from Microsoft:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by jart** [comment]
Awesome! I'll take a look over the weekend.

**Comment by jart** [comment]
It seems those free VMs are 32-bit only. No matter. I found my Windows 7 disk and key. I'll push a fix soon.

Does Windows 7 x64 really disallow 64-bit pointers?

```c
static char *AllocateMemory(void *addr, size_t size, int64_t *h) {
  return MapViewOfFileExNuma(
      (*h = CreateFileMappingNuma(-1, NULL, pushpop(kNtPageExecuteReadwrite), 0,
                                  size, NULL, kNtNumaNoPreferredNode)),
      kNtFileMapRead | kNtFileMapWrite, 0, 0, size, addr,
      kNtNumaNoPreferredNode);
}
````

I want to be able to pass an explicit `addr` to that function which is above 0x100000000 and have WIN32 not return 0. It matters because cosmo wants to choose an addresses for `mmap(NULL, ....)` above 0x0000100080000000 since it guarantees non-fixed mappings won't conflict with address sanitizer poison due to `'((2**47)>>3)+0x7fff8000`. If you know a workaround, let me know!

Cosmopolitan is the only C library that implements UNIX polyfills for Windows under a permissive license. Considerable effort went into making that possible, although it's still rough around the edges. Thank you again for the report and for any continued support you choose to lend to this effort.
