### ISSUE TITLE
Error running Redbean on Windows after adding files via WinRAR

### ISSUE THREAD

**Issue by rovashan** [jart/cosmopolitan#53]
1. Opened zip in WinRAR 5.30 (32-bit). 
2. Added gif to tool/net.
3. Saved archive with default settings.

![redbead-error](https://user-images.githubusercontent.com/4746551/109292791-9564ab80-7833-11eb-9924-3a12d64b6bff.PNG)
![sysinfo](https://user-images.githubusercontent.com/4746551/109292804-9990c900-7833-11eb-809e-5c7517102601.PNG)

**Comment by avioli** [comment]
Don’t use winrar?

**Comment by rovashan** [comment]
> Don’t use winrar?

What do you suggest?

**Comment by jart** [comment]
Thanks for filing this report. I fixed this issue in https://github.com/jart/cosmopolitan/commit/218ef491476f15abb980ee89bf69344913a4c51d and pushed a new binary release here: https://justine.lol/redbean/index.html It turned out to not be related to WinRAR. So please take a look and leave a comment to confirm that WinRAR works good for you after this change.

**Comment by jart** [comment]
I'm consolidating this issue into #68 for posterity. Thanks again for the report.

**Comment by rovashan** [comment]
Just tested with new binary and I still cannot get it running after saving the archive.
I only replaced redbean.html then it bombs out.

Please see attached screenshot and archive.

![image](https://user-images.githubusercontent.com/4746551/109405713-031bef00-797c-11eb-9975-d38fd3dd2bb7.png)

[redbean-2021-02-27.zip](https://github.com/jart/cosmopolitan/files/6056179/redbean-2021-02-27.zip)
